import 'package:flutter/material.dart';
import 'category.dart';
import 'recipe.dart';

const CATEGORIES = [
  Category(title: 'Italian', id: 'c1', color: Colors.redAccent),
  Category(title: 'Indian', id: 'c2', color: Colors.redAccent),
  Category(title: 'Quick & Easy', id: 'c3', color: Colors.redAccent),
  Category(title: 'Under £1', id: 'c4', color: Colors.redAccent),
  Category(title: 'Breakfast', id: 'c5', color: Colors.redAccent),
  Category(title: 'Mexican', id: 'c6', color: Colors.redAccent),
  Category(title: 'Jamaican', id: 'c7', color: Colors.redAccent),
  Category(title: 'Chinese', id: 'c8', color: Colors.redAccent),
  Category(title: 'Thai', id: 'c9', color: Colors.redAccent),
  Category(title: 'Healthy', id: 'c10', color: Colors.redAccent),
];

const RECIPES = const [
  Recipe(
    id: 'm1',
    categories: ['c1'],
    title: 'Tuna pasta bake',
    imageUrl: 'https://cdn.pixabay.com/photo/2015/10/23/11/17/eat-1002825_960_720.jpg',
    ingredients: [
      '600g penne',
      '50g butter',
      '50g plain flour'
          '600ml milk'
          '250g grated cheddar',
      '2 x 160g tuna, drained',
      '330g canned sweetcorn, drained',
      'handful of chopped parsley'
    ],
    steps: [
      'Boil 600g rigatoni for 2 mins less time than stated on the pack'
    'To make the sauce, melt 50g butter in a saucepan and stir in 50g plain flour'
    'Cook for 1 min, then gradually stir in 600ml milk to make a thick white sauce',
    'Remove from the heat and stir in all but a handful of the 250g grated cheddar',
      'Drain the pasta, mix with the white sauce, two 160g drained cans tuna, one 330g drained can sweetcorn and a large handful of chopped parsley, then season',
      'Transfer to a baking dish and top with the rest of the grated cheddar.',
      'Bake for 15-20 mins until the cheese on top is golden and starting to brown.',
    ],
    duration: 40,
    complexity: Complexity.Rookie,
    affordability: Affordability.Cheap,
    isVegan: false,
    isVeggie: true,
  ),
  Recipe(
    id: 'm2',
    categories: ['c7'],
    title: 'Spicy jerk potato & pineapple hash',
    imageUrl: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/spicy-jerk-pineapple-hash--2e802a0.jpg?quality=90&webp=true&resize=300,272',
    ingredients: ['700g Maris Piper potatoes, cut into medium chunks'
    '1tbsp vegetable oil',
      '4 rashers streaky bacon, cut into bite-sized pieces',
      '40g unsalted butter',
      '1/2 tbsp jerk seasoning',
      '200g pineapple chunks',
      '4 large eggs',
      '1/2 small pack coriander, chopped',
      '1/2 red chilli, thinly sliced'
    ],
    steps: ['Bring a large pan of lightly salted water to the boil. Add the potatoes and boil for 7 mins, then drain and leave to steam-dry for 5 mins. Meanwhile, heat the oil in a large frying pan over a medium heat and fry the bacon for 5 mins until crispy.',
    'Add the butter to the pan along with the potatoes and seasoning, and fry over a medium heat, turning occasionally, for 12 mins. Nestle the pineapple chunks in the pan and cook for a further 3 mins',
      'Crack the eggs over the potatoes, cover the pan with a lid or large plate and cook for 5-6 mins over a medium-low heat until the whites are just set and the yolks are still runny. Finish with the coriander and a spri',
    ],
    duration: 35,
    complexity: Complexity.Rookie,
    affordability: Affordability.Cheap,
    isVegan: false,
    isVeggie: false,
  ),
  Recipe(
    id: 'm3',
    categories: ['c10', 'c3', 'c4'],
    title: 'Tuna sweet potato jackets',
    imageUrl: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-265510_12-8e750a5.jpg?quality=90&webp=true&resize=440,400',
    ingredients: ['4 small sweet potatoes',
    '1 can of tuna, drained',
      '1/2 red onion, finely sliced',
      '1 small red chilli, de-seeded and chopped',
      'juice of 1 lime',
      '6 tbsp Greek yogurt',
      'handful coriander leaves',

    ],
    steps: ['Scrub the sweet potatoes and prick all over with a fork. Place on a microwaveable plate and cook on High for 18-20 mins, or until tender. Split in half and place each one, cut-side up, on a serving plate.'
    'Flake the drained tuna with a fork and divide between the sweet potatoes. Top with the red onion and chilli, then squeeze over the lime juice. Top with a dollop of yogurt and scatter over the coriander, to serve.',

    ],
    duration: 30,
    complexity: Complexity.Rookie,
    affordability: Affordability.Cheap,
    isVegan: false,
    isVeggie: true,
  ),
  Recipe(
    id: 'm1',
    categories: ['c1'],
    title: 'title',
    imageUrl: 'imageUrl',
    ingredients: [''],
    steps: [''],
    duration: 10,
    complexity: Complexity.Rookie,
    affordability: Affordability.Cheap,
    isVegan: false,
    isVeggie: true,
  ),
  Recipe(
    id: 'm1',
    categories: ['c1'],
    title: 'title',
    imageUrl: 'imageUrl',
    ingredients: [''],
    steps: [''],
    duration: 10,
    complexity: Complexity.Rookie,
    affordability: Affordability.Cheap,
    isVegan: false,
    isVeggie: true,
  ),
  Recipe(
    id: 'm1',
    categories: ['c1'],
    title: 'title',
    imageUrl: 'imageUrl',
    ingredients: [''],
    steps: [''],
    duration: 10,
    complexity: Complexity.Rookie,
    affordability: Affordability.Cheap,
    isVegan: false,
    isVeggie: true,
  ),
  Recipe(
    id: 'm1',
    categories: ['c1'],
    title: 'title',
    imageUrl: 'imageUrl',
    ingredients: [''],
    steps: [''],
    duration: 10,
    complexity: Complexity.Rookie,
    affordability: Affordability.Cheap,
    isVegan: false,
    isVeggie: true,
  ),
  Recipe(
    id: 'm1',
    categories: ['c1'],
    title: 'title',
    imageUrl: 'imageUrl',
    ingredients: [''],
    steps: [''],
    duration: 10,
    complexity: Complexity.Rookie,
    affordability: Affordability.Cheap,
    isVegan: false,
    isVeggie: true,
  ),
  Recipe(
    id: 'm1',
    categories: ['c1'],
    title: 'title',
    imageUrl: 'imageUrl',
    ingredients: [''],
    steps: [''],
    duration: 10,
    complexity: Complexity.Rookie,
    affordability: Affordability.Cheap,
    isVegan: false,
    isVeggie: true,
  ),
  Recipe(
    id: 'm1',
    categories: ['c1'],
    title: 'title',
    imageUrl: 'imageUrl',
    ingredients: [''],
    steps: [''],
    duration: 10,
    complexity: Complexity.Rookie,
    affordability: Affordability.Cheap,
    isVegan: false,
    isVeggie: true,
  ),
  Recipe(
    id: 'm1',
    categories: ['c1'],
    title: 'title',
    imageUrl: 'imageUrl',
    ingredients: [''],
    steps: [''],
    duration: 10,
    complexity: Complexity.Rookie,
    affordability: Affordability.Cheap,
    isVegan: false,
    isVeggie: true,
  ),
  Recipe(
    id: 'm1',
    categories: ['c1'],
    title: 'title',
    imageUrl: 'imageUrl',
    ingredients: [''],
    steps: [''],
    duration: 10,
    complexity: Complexity.Rookie,
    affordability: Affordability.Cheap,
    isVegan: false,
    isVeggie: true,
  ),
  Recipe(
    id: 'm1',
    categories: ['c1'],
    title: 'title',
    imageUrl: 'imageUrl',
    ingredients: [''],
    steps: [''],
    duration: 10,
    complexity: Complexity.Rookie,
    affordability: Affordability.Cheap,
    isVegan: false,
    isVeggie: true,
  ),
];
